<?php

use Drupal\Core\Template\Attribute;
use Drupal\node\Entity\Node;

function wunderpage_theme_suggestions_page_alter(&$suggestions, $variables) {
  $suggestions[] = 'page__node__type_landingpage';
}

function wunderpage_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'field__paragraph';
}

function wunderpage_preprocess_page(&$variables) {
  if (($node = \Drupal::routeMatch()->getParameter('node')) && $node instanceof \Drupal\node\NodeInterface) {
    if($node->getType() == 'landingpage'){
      $variables['#attached']['library'][] = 'wunderpage/base-style';
    }
  }
}

function wunderpage_preprocess_paragraph(&$variables) {
  // Task: find better way to get the field value
  $block_id = $variables['content']['field_block_id'][0]['#context']['value'];
  $variables['block_output'] = '';

  if($block = \Drupal\block\Entity\Block::load($block_id)){
    $variables['block_output'] = \Drupal::entityManager()
  ->getViewBuilder('block')
  ->view($block);
  }

}

/**
 * Implements hook_theme().
 */
function wunderpage_theme() {
  return array(
    'paragraph__wunderpage_row' => array(
      'preprocess functions' => array(
        'template_preprocess_paragraph',
        )
    ),
    'paragraph__content_paragraph' => array(
      'preprocess functions' => array(
        'template_preprocess_paragraph',
        )
    ),
    'paragraph__menu_list_paragraph' => array(
      'preprocess functions' => array(
        'template_preprocess_paragraph',
        )
    ),
    'paragraph__hero_card_paragraph' => array(
      'preprocess functions' => array(
        'template_preprocess_paragraph',
        )
    ),
    'paragraph__block_column_paragraph' => array(
      'preprocess functions' => array(
        'template_preprocess_paragraph',
        'wunderpage_preprocess_paragraph',
        )
    ),
    // 'page__node__type_landingpage' => array(
    //   'preprocess functions' => array(
    //     'template_preprocess_page',
    //     )
    // ),
    'field__paragraph' => array(
      'preprocess functions' => array(
        'template_preprocess_field',
        )
    ),
  );
}


